import hashlib
import functools
import logging
from collections import OrderedDict

logger = logging.getLogger(__name__)

class CacheManager:
    """
    LRU Cache implementation for fast inference caching.
    Caches the exact JSON payload generated by the ensemble predictor, 
    keyed by the SHA-256 hash of the uploaded image bytes.
    """
    def __init__(self, capacity: int = 100):
        self.capacity = capacity
        self.cache = OrderedDict()

    def get_hash(self, file_path: str) -> str:
        """Generates a SHA-256 hash of the file content."""
        hasher = hashlib.sha256()
        try:
            with open(file_path, 'rb') as f:
                # Read in chunks to avoid high memory spikes
                for chunk in iter(lambda: f.read(4096), b""):
                    hasher.update(chunk)
            return hasher.hexdigest()
        except Exception as e:
            logger.error(f"Cache hashing error: {e}")
            return None

    def get(self, key: str):
        if key not in self.cache:
            return None
        self.cache.move_to_end(key)
        return self.cache[key]

    def set(self, key: str, value: dict):
        if not key:
            return
        if key in self.cache:
            self.cache.move_to_end(key)
        self.cache[key] = value
        if len(self.cache) > self.capacity:
            self.cache.popitem(last=False) # Remove oldest

# Global singleton
inference_cache = CacheManager(capacity=100)
